// Code generated by MockGen. DO NOT EDIT.
// Source: base.go
//
// Generated by this command:
//
//	mockgen -source=base.go -destination=mocks/mock_base.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	db "github.com/alxaxenov/ya-gophermart/internal/config/db"
	gomock "go.uber.org/mock/gomock"
)

// Mockconnector is a mock of connector interface.
type Mockconnector struct {
	ctrl     *gomock.Controller
	recorder *MockconnectorMockRecorder
	isgomock struct{}
}

// MockconnectorMockRecorder is the mock recorder for Mockconnector.
type MockconnectorMockRecorder struct {
	mock *Mockconnector
}

// NewMockconnector creates a new mock instance.
func NewMockconnector(ctrl *gomock.Controller) *Mockconnector {
	mock := &Mockconnector{ctrl: ctrl}
	mock.recorder = &MockconnectorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *Mockconnector) EXPECT() *MockconnectorMockRecorder {
	return m.recorder
}

// GetDB mocks base method.
func (m *Mockconnector) GetDB() db.DB {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDB")
	ret0, _ := ret[0].(db.DB)
	return ret0
}

// GetDB indicates an expected call of GetDB.
func (mr *MockconnectorMockRecorder) GetDB() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDB", reflect.TypeOf((*Mockconnector)(nil).GetDB))
}
