// Code generated by MockGen. DO NOT EDIT.
// Source: user_service.go
//
// Generated by this command:
//
//	mockgen -source=user_service.go -destination=mocks/mock_user_service.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	model "github.com/alxaxenov/ya-gophermart/internal/repo/model"
	gomock "go.uber.org/mock/gomock"
)

// MockexpectedRepo is a mock of expectedRepo interface.
type MockexpectedRepo struct {
	ctrl     *gomock.Controller
	recorder *MockexpectedRepoMockRecorder
	isgomock struct{}
}

// MockexpectedRepoMockRecorder is the mock recorder for MockexpectedRepo.
type MockexpectedRepoMockRecorder struct {
	mock *MockexpectedRepo
}

// NewMockexpectedRepo creates a new mock instance.
func NewMockexpectedRepo(ctrl *gomock.Controller) *MockexpectedRepo {
	mock := &MockexpectedRepo{ctrl: ctrl}
	mock.recorder = &MockexpectedRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockexpectedRepo) EXPECT() *MockexpectedRepoMockRecorder {
	return m.recorder
}

// CheckLogin mocks base method.
func (m *MockexpectedRepo) CheckLogin(arg0 context.Context, arg1 string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CheckLogin", arg0, arg1)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CheckLogin indicates an expected call of CheckLogin.
func (mr *MockexpectedRepoMockRecorder) CheckLogin(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CheckLogin", reflect.TypeOf((*MockexpectedRepo)(nil).CheckLogin), arg0, arg1)
}

// CreateUser mocks base method.
func (m *MockexpectedRepo) CreateUser(arg0 context.Context, arg1, arg2 string) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateUser", arg0, arg1, arg2)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateUser indicates an expected call of CreateUser.
func (mr *MockexpectedRepoMockRecorder) CreateUser(arg0, arg1, arg2 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateUser", reflect.TypeOf((*MockexpectedRepo)(nil).CreateUser), arg0, arg1, arg2)
}

// GetUser mocks base method.
func (m *MockexpectedRepo) GetUser(arg0 context.Context, arg1 string) (*model.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUser", arg0, arg1)
	ret0, _ := ret[0].(*model.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUser indicates an expected call of GetUser.
func (mr *MockexpectedRepoMockRecorder) GetUser(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUser", reflect.TypeOf((*MockexpectedRepo)(nil).GetUser), arg0, arg1)
}

// MockHash is a mock of Hash interface.
type MockHash struct {
	ctrl     *gomock.Controller
	recorder *MockHashMockRecorder
	isgomock struct{}
}

// MockHashMockRecorder is the mock recorder for MockHash.
type MockHashMockRecorder struct {
	mock *MockHash
}

// NewMockHash creates a new mock instance.
func NewMockHash(ctrl *gomock.Controller) *MockHash {
	mock := &MockHash{ctrl: ctrl}
	mock.recorder = &MockHashMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockHash) EXPECT() *MockHashMockRecorder {
	return m.recorder
}

// CheckPass mocks base method.
func (m *MockHash) CheckPass(arg0, arg1 string) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CheckPass", arg0, arg1)
	ret0, _ := ret[0].(bool)
	return ret0
}

// CheckPass indicates an expected call of CheckPass.
func (mr *MockHashMockRecorder) CheckPass(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CheckPass", reflect.TypeOf((*MockHash)(nil).CheckPass), arg0, arg1)
}

// HashPass mocks base method.
func (m *MockHash) HashPass(arg0 string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HashPass", arg0)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// HashPass indicates an expected call of HashPass.
func (mr *MockHashMockRecorder) HashPass(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HashPass", reflect.TypeOf((*MockHash)(nil).HashPass), arg0)
}
