// Code generated by MockGen. DO NOT EDIT.
// Source: gophermart_service.go
//
// Generated by this command:
//
//	mockgen -source=gophermart_service.go -destination=mocks/mock_gophermart_service.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	db "github.com/alxaxenov/ya-gophermart/internal/config/db"
	model "github.com/alxaxenov/ya-gophermart/internal/repo/model"
	gomock "go.uber.org/mock/gomock"
)

// MockexpectedRepo is a mock of expectedRepo interface.
type MockexpectedRepo struct {
	ctrl     *gomock.Controller
	recorder *MockexpectedRepoMockRecorder
	isgomock struct{}
}

// MockexpectedRepoMockRecorder is the mock recorder for MockexpectedRepo.
type MockexpectedRepoMockRecorder struct {
	mock *MockexpectedRepo
}

// NewMockexpectedRepo creates a new mock instance.
func NewMockexpectedRepo(ctrl *gomock.Controller) *MockexpectedRepo {
	mock := &MockexpectedRepo{ctrl: ctrl}
	mock.recorder = &MockexpectedRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockexpectedRepo) EXPECT() *MockexpectedRepoMockRecorder {
	return m.recorder
}

// AddWithdrawTx mocks base method.
func (m *MockexpectedRepo) AddWithdrawTx(arg0 context.Context, arg1 db.Tx, arg2 *model.AddWithdraw) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddWithdrawTx", arg0, arg1, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddWithdrawTx indicates an expected call of AddWithdrawTx.
func (mr *MockexpectedRepoMockRecorder) AddWithdrawTx(arg0, arg1, arg2 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddWithdrawTx", reflect.TypeOf((*MockexpectedRepo)(nil).AddWithdrawTx), arg0, arg1, arg2)
}

// CreateOrder mocks base method.
func (m *MockexpectedRepo) CreateOrder(arg0 context.Context, arg1 int, arg2 string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateOrder", arg0, arg1, arg2)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateOrder indicates an expected call of CreateOrder.
func (mr *MockexpectedRepoMockRecorder) CreateOrder(arg0, arg1, arg2 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateOrder", reflect.TypeOf((*MockexpectedRepo)(nil).CreateOrder), arg0, arg1, arg2)
}

// GetBalance mocks base method.
func (m *MockexpectedRepo) GetBalance(arg0 context.Context, arg1 int) (*model.Balance, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBalance", arg0, arg1)
	ret0, _ := ret[0].(*model.Balance)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetBalance indicates an expected call of GetBalance.
func (mr *MockexpectedRepoMockRecorder) GetBalance(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBalance", reflect.TypeOf((*MockexpectedRepo)(nil).GetBalance), arg0, arg1)
}

// GetBalanceTx mocks base method.
func (m *MockexpectedRepo) GetBalanceTx(arg0 context.Context, arg1 int) (*model.Balance, db.Tx, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBalanceTx", arg0, arg1)
	ret0, _ := ret[0].(*model.Balance)
	ret1, _ := ret[1].(db.Tx)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetBalanceTx indicates an expected call of GetBalanceTx.
func (mr *MockexpectedRepoMockRecorder) GetBalanceTx(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBalanceTx", reflect.TypeOf((*MockexpectedRepo)(nil).GetBalanceTx), arg0, arg1)
}

// GetOrderByNumber mocks base method.
func (m *MockexpectedRepo) GetOrderByNumber(arg0 context.Context, arg1 string) (*model.Order, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetOrderByNumber", arg0, arg1)
	ret0, _ := ret[0].(*model.Order)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetOrderByNumber indicates an expected call of GetOrderByNumber.
func (mr *MockexpectedRepoMockRecorder) GetOrderByNumber(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetOrderByNumber", reflect.TypeOf((*MockexpectedRepo)(nil).GetOrderByNumber), arg0, arg1)
}

// GetOrders mocks base method.
func (m *MockexpectedRepo) GetOrders(ctx context.Context, userID int) (*[]model.OrderForList, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetOrders", ctx, userID)
	ret0, _ := ret[0].(*[]model.OrderForList)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetOrders indicates an expected call of GetOrders.
func (mr *MockexpectedRepoMockRecorder) GetOrders(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetOrders", reflect.TypeOf((*MockexpectedRepo)(nil).GetOrders), ctx, userID)
}

// GetUserWithdrawals mocks base method.
func (m *MockexpectedRepo) GetUserWithdrawals(arg0 context.Context, arg1 int) (*[]model.Withdraw, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserWithdrawals", arg0, arg1)
	ret0, _ := ret[0].(*[]model.Withdraw)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserWithdrawals indicates an expected call of GetUserWithdrawals.
func (mr *MockexpectedRepoMockRecorder) GetUserWithdrawals(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserWithdrawals", reflect.TypeOf((*MockexpectedRepo)(nil).GetUserWithdrawals), arg0, arg1)
}
