// Code generated by MockGen. DO NOT EDIT.
// Source: accrual_updater.go
//
// Generated by this command:
//
//	mockgen -source=accrual_updater.go -destination=mocks/mock_accrual_updater.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	accrual "github.com/alxaxenov/ya-gophermart/internal/client/accrual"
	order "github.com/alxaxenov/ya-gophermart/internal/domain/order"
	model "github.com/alxaxenov/ya-gophermart/internal/repo/model"
	gomock "go.uber.org/mock/gomock"
)

// MockgophermartRepo is a mock of gophermartRepo interface.
type MockgophermartRepo struct {
	ctrl     *gomock.Controller
	recorder *MockgophermartRepoMockRecorder
	isgomock struct{}
}

// MockgophermartRepoMockRecorder is the mock recorder for MockgophermartRepo.
type MockgophermartRepoMockRecorder struct {
	mock *MockgophermartRepo
}

// NewMockgophermartRepo creates a new mock instance.
func NewMockgophermartRepo(ctrl *gomock.Controller) *MockgophermartRepo {
	mock := &MockgophermartRepo{ctrl: ctrl}
	mock.recorder = &MockgophermartRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockgophermartRepo) EXPECT() *MockgophermartRepoMockRecorder {
	return m.recorder
}

// GetOrdersToProcess mocks base method.
func (m *MockgophermartRepo) GetOrdersToProcess(arg0 context.Context, arg1 int) (*[]model.OrderToProcess, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetOrdersToProcess", arg0, arg1)
	ret0, _ := ret[0].(*[]model.OrderToProcess)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetOrdersToProcess indicates an expected call of GetOrdersToProcess.
func (mr *MockgophermartRepoMockRecorder) GetOrdersToProcess(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetOrdersToProcess", reflect.TypeOf((*MockgophermartRepo)(nil).GetOrdersToProcess), arg0, arg1)
}

// UpdateOrderAccrual mocks base method.
func (m *MockgophermartRepo) UpdateOrderAccrual(arg0 context.Context, arg1 string, arg2 int, arg3 order.Status, arg4 float64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateOrderAccrual", arg0, arg1, arg2, arg3, arg4)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateOrderAccrual indicates an expected call of UpdateOrderAccrual.
func (mr *MockgophermartRepoMockRecorder) UpdateOrderAccrual(arg0, arg1, arg2, arg3, arg4 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateOrderAccrual", reflect.TypeOf((*MockgophermartRepo)(nil).UpdateOrderAccrual), arg0, arg1, arg2, arg3, arg4)
}

// UpdateOrderStatus mocks base method.
func (m *MockgophermartRepo) UpdateOrderStatus(arg0 context.Context, arg1 string, arg2 order.Status) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateOrderStatus", arg0, arg1, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateOrderStatus indicates an expected call of UpdateOrderStatus.
func (mr *MockgophermartRepoMockRecorder) UpdateOrderStatus(arg0, arg1, arg2 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateOrderStatus", reflect.TypeOf((*MockgophermartRepo)(nil).UpdateOrderStatus), arg0, arg1, arg2)
}

// MockaccrualClient is a mock of accrualClient interface.
type MockaccrualClient struct {
	ctrl     *gomock.Controller
	recorder *MockaccrualClientMockRecorder
	isgomock struct{}
}

// MockaccrualClientMockRecorder is the mock recorder for MockaccrualClient.
type MockaccrualClientMockRecorder struct {
	mock *MockaccrualClient
}

// NewMockaccrualClient creates a new mock instance.
func NewMockaccrualClient(ctrl *gomock.Controller) *MockaccrualClient {
	mock := &MockaccrualClient{ctrl: ctrl}
	mock.recorder = &MockaccrualClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockaccrualClient) EXPECT() *MockaccrualClientMockRecorder {
	return m.recorder
}

// GetOrderInfo mocks base method.
func (m *MockaccrualClient) GetOrderInfo(arg0 string) (*accrual.OrderInfo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetOrderInfo", arg0)
	ret0, _ := ret[0].(*accrual.OrderInfo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetOrderInfo indicates an expected call of GetOrderInfo.
func (mr *MockaccrualClientMockRecorder) GetOrderInfo(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetOrderInfo", reflect.TypeOf((*MockaccrualClient)(nil).GetOrderInfo), arg0)
}

// Mockthrottler is a mock of throttler interface.
type Mockthrottler struct {
	ctrl     *gomock.Controller
	recorder *MockthrottlerMockRecorder
	isgomock struct{}
}

// MockthrottlerMockRecorder is the mock recorder for Mockthrottler.
type MockthrottlerMockRecorder struct {
	mock *Mockthrottler
}

// NewMockthrottler creates a new mock instance.
func NewMockthrottler(ctrl *gomock.Controller) *Mockthrottler {
	mock := &Mockthrottler{ctrl: ctrl}
	mock.recorder = &MockthrottlerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *Mockthrottler) EXPECT() *MockthrottlerMockRecorder {
	return m.recorder
}

// UpdateNextRequestAllowed mocks base method.
func (m *Mockthrottler) UpdateNextRequestAllowed(arg0 int) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "UpdateNextRequestAllowed", arg0)
}

// UpdateNextRequestAllowed indicates an expected call of UpdateNextRequestAllowed.
func (mr *MockthrottlerMockRecorder) UpdateNextRequestAllowed(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateNextRequestAllowed", reflect.TypeOf((*Mockthrottler)(nil).UpdateNextRequestAllowed), arg0)
}

// WaitUntilNextRequestAllowed mocks base method.
func (m *Mockthrottler) WaitUntilNextRequestAllowed(arg0 context.Context) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WaitUntilNextRequestAllowed", arg0)
	ret0, _ := ret[0].(bool)
	return ret0
}

// WaitUntilNextRequestAllowed indicates an expected call of WaitUntilNextRequestAllowed.
func (mr *MockthrottlerMockRecorder) WaitUntilNextRequestAllowed(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WaitUntilNextRequestAllowed", reflect.TypeOf((*Mockthrottler)(nil).WaitUntilNextRequestAllowed), arg0)
}
