// Code generated by MockGen. DO NOT EDIT.
// Source: server.go
//
// Generated by this command:
//
//	mockgen -source=server.go -destination=mocks/mock_handler.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	model "github.com/alxaxenov/ya-gophermart/internal/model"
	gomock "go.uber.org/mock/gomock"
)

// MockUserService is a mock of UserService interface.
type MockUserService struct {
	ctrl     *gomock.Controller
	recorder *MockUserServiceMockRecorder
	isgomock struct{}
}

// MockUserServiceMockRecorder is the mock recorder for MockUserService.
type MockUserServiceMockRecorder struct {
	mock *MockUserService
}

// NewMockUserService creates a new mock instance.
func NewMockUserService(ctrl *gomock.Controller) *MockUserService {
	mock := &MockUserService{ctrl: ctrl}
	mock.recorder = &MockUserServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUserService) EXPECT() *MockUserServiceMockRecorder {
	return m.recorder
}

// BuildTokenString mocks base method.
func (m *MockUserService) BuildTokenString(arg0 int) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BuildTokenString", arg0)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// BuildTokenString indicates an expected call of BuildTokenString.
func (mr *MockUserServiceMockRecorder) BuildTokenString(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BuildTokenString", reflect.TypeOf((*MockUserService)(nil).BuildTokenString), arg0)
}

// GetCookieAuthKey mocks base method.
func (m *MockUserService) GetCookieAuthKey() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCookieAuthKey")
	ret0, _ := ret[0].(string)
	return ret0
}

// GetCookieAuthKey indicates an expected call of GetCookieAuthKey.
func (mr *MockUserServiceMockRecorder) GetCookieAuthKey() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCookieAuthKey", reflect.TypeOf((*MockUserService)(nil).GetCookieAuthKey))
}

// GetUserIDCtx mocks base method.
func (m *MockUserService) GetUserIDCtx(arg0 context.Context) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserIDCtx", arg0)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserIDCtx indicates an expected call of GetUserIDCtx.
func (mr *MockUserServiceMockRecorder) GetUserIDCtx(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserIDCtx", reflect.TypeOf((*MockUserService)(nil).GetUserIDCtx), arg0)
}

// LoginUser mocks base method.
func (m *MockUserService) LoginUser(arg0 context.Context, arg1, arg2 string) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LoginUser", arg0, arg1, arg2)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// LoginUser indicates an expected call of LoginUser.
func (mr *MockUserServiceMockRecorder) LoginUser(arg0, arg1, arg2 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LoginUser", reflect.TypeOf((*MockUserService)(nil).LoginUser), arg0, arg1, arg2)
}

// RegisterUser mocks base method.
func (m *MockUserService) RegisterUser(arg0 context.Context, arg1, arg2 string) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RegisterUser", arg0, arg1, arg2)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RegisterUser indicates an expected call of RegisterUser.
func (mr *MockUserServiceMockRecorder) RegisterUser(arg0, arg1, arg2 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RegisterUser", reflect.TypeOf((*MockUserService)(nil).RegisterUser), arg0, arg1, arg2)
}

// MockGophermartService is a mock of GophermartService interface.
type MockGophermartService struct {
	ctrl     *gomock.Controller
	recorder *MockGophermartServiceMockRecorder
	isgomock struct{}
}

// MockGophermartServiceMockRecorder is the mock recorder for MockGophermartService.
type MockGophermartServiceMockRecorder struct {
	mock *MockGophermartService
}

// NewMockGophermartService creates a new mock instance.
func NewMockGophermartService(ctrl *gomock.Controller) *MockGophermartService {
	mock := &MockGophermartService{ctrl: ctrl}
	mock.recorder = &MockGophermartServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockGophermartService) EXPECT() *MockGophermartServiceMockRecorder {
	return m.recorder
}

// AddWithdraw mocks base method.
func (m *MockGophermartService) AddWithdraw(arg0 context.Context, arg1 int, arg2 string, arg3 float64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddWithdraw", arg0, arg1, arg2, arg3)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddWithdraw indicates an expected call of AddWithdraw.
func (mr *MockGophermartServiceMockRecorder) AddWithdraw(arg0, arg1, arg2, arg3 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddWithdraw", reflect.TypeOf((*MockGophermartService)(nil).AddWithdraw), arg0, arg1, arg2, arg3)
}

// CreateOrder mocks base method.
func (m *MockGophermartService) CreateOrder(arg0 context.Context, arg1 int, arg2 string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateOrder", arg0, arg1, arg2)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateOrder indicates an expected call of CreateOrder.
func (mr *MockGophermartServiceMockRecorder) CreateOrder(arg0, arg1, arg2 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateOrder", reflect.TypeOf((*MockGophermartService)(nil).CreateOrder), arg0, arg1, arg2)
}

// GetBalance mocks base method.
func (m *MockGophermartService) GetBalance(arg0 context.Context, arg1 int) (*model.UserBalanceResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBalance", arg0, arg1)
	ret0, _ := ret[0].(*model.UserBalanceResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetBalance indicates an expected call of GetBalance.
func (mr *MockGophermartServiceMockRecorder) GetBalance(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBalance", reflect.TypeOf((*MockGophermartService)(nil).GetBalance), arg0, arg1)
}

// GetOrders mocks base method.
func (m *MockGophermartService) GetOrders(arg0 context.Context, arg1 int) (*[]model.GetOrdersResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetOrders", arg0, arg1)
	ret0, _ := ret[0].(*[]model.GetOrdersResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetOrders indicates an expected call of GetOrders.
func (mr *MockGophermartServiceMockRecorder) GetOrders(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetOrders", reflect.TypeOf((*MockGophermartService)(nil).GetOrders), arg0, arg1)
}

// GetWithdrawals mocks base method.
func (m *MockGophermartService) GetWithdrawals(arg0 context.Context, arg1 int) (*[]model.GetWithdrawResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetWithdrawals", arg0, arg1)
	ret0, _ := ret[0].(*[]model.GetWithdrawResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetWithdrawals indicates an expected call of GetWithdrawals.
func (mr *MockGophermartServiceMockRecorder) GetWithdrawals(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetWithdrawals", reflect.TypeOf((*MockGophermartService)(nil).GetWithdrawals), arg0, arg1)
}
